### ISSUE TITLE
More Information and Links for Recommendations

### ISSUE THREAD

**Issue by Sandesh-L** [hjbr22/ACCESS_Project#96]
After an RP is recommended to the user, we want to let them know a little more about the RP.

When the dropdown button is clicked it should give a little blurb about the RP. Then have a link to view the RP's documentation (the one on Confluence). It should also have a link to the ACCESS page where they can request an allocation. 
After this would be shown why they were shown these recommendations.

**Comment by Bodhi-Rubinstein** [comment]
finished
